# Generated by Django 3.0.dev20190304153508 on 2019-08-12 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyCompetition',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Competition')),
            ],
            bases=('base.competition',),
        ),
        migrations.CreateModel(
            name='FantasyPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Player')),
            ],
            bases=('base.player',),
        ),
        migrations.CreateModel(
            name='FantasySeason',
            fields=[
                ('season_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Season')),
            ],
            bases=('base.season',),
        ),
        migrations.CreateModel(
            name='FantasyStatistic',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Statistic')),
            ],
            bases=('base.statistic',),
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Team')),
            ],
            bases=('base.team',),
        ),
        migrations.CreateModel(
            name='FantasyVenue',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Venue')),
            ],
            bases=('base.venue',),
        ),
        migrations.CreateModel(
            name='FantasyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('favorite_player', models.CharField(default='Siffert4ever', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
            },
        ),
    ]
