# Generated by Django 3.0.dev20190304153508 on 2019-08-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialCompetition',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Competition')),
            ],
            bases=('base.competition',),
        ),
        migrations.CreateModel(
            name='OfficialPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Player')),
            ],
            bases=('base.player',),
        ),
        migrations.CreateModel(
            name='OfficialSeason',
            fields=[
                ('season_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Season')),
            ],
            bases=('base.season',),
        ),
        migrations.CreateModel(
            name='OfficialSportEvent',
            fields=[
                ('sportevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.SportEvent')),
            ],
            bases=('base.sportevent',),
        ),
        migrations.CreateModel(
            name='OfficialStatistic',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Statistic')),
            ],
            bases=('base.statistic',),
        ),
        migrations.CreateModel(
            name='OfficialTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Team')),
            ],
            bases=('base.team',),
        ),
        migrations.CreateModel(
            name='OfficialVenue',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Venue')),
            ],
            bases=('base.venue',),
        ),
    ]
