# Generated by Django 3.0.dev20190304153508 on 2019-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=256)),
                ('away_team', models.CharField(max_length=256)),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('competition_name', models.CharField(max_length=256)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
