# Generated by Django 3.0.dev20190304153508 on 2019-03-06 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_event',
            name='away_team',
            field=models.CharField(default='<home team>', max_length=256),
        ),
        migrations.AlterField(
            model_name='sport_event',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sport_event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 19, 43, 46, 135831, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sport_event',
            name='home_team',
            field=models.CharField(default='<home team>', max_length=256),
        ),
        migrations.AlterField(
            model_name='sport_event',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
