# Generated by Django 3.0.dev20190304153508 on 2019-03-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190306_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
