# Generated by Django 3.0.dev20190304153508 on 2019-03-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(default='', max_length=256)),
                ('country_code', models.CharField(default='', max_length=4)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('jersey_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.CharField(max_length=10)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('event_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('suspensions', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('seven_m_goals', models.IntegerField()),
                ('field_goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('technical_fouls', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.SportEvent')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('country_code', models.CharField(default='', max_length=4)),
                ('abbreviation', models.CharField(default='', max_length=10)),
                ('competitions', models.ManyToManyField(to='stats.Competition')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Player')),
            ],
        ),
        migrations.DeleteModel(
            name='Sport_event',
        ),
        migrations.AddField(
            model_name='sportevent',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='competition_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Competition'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Team'),
        ),
    ]
