# Generated by Django 3.0.dev20190304153508 on 2019-03-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_season_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='competition',
            new_name='competition_id',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='teams',
            new_name='team_ids',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='player',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='competitions',
            new_name='competition_ids',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=64),
        ),
    ]
