# Generated by Django 3.0.dev20190304153508 on 2019-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20190320_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
