# Generated by Django 3.0.dev20190304153508 on 2019-03-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20190320_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Team'),
        ),
    ]
