# Generated by Django 3.0.dev20190304153508 on 2019-03-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_venue_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='competition_name',
        ),
        migrations.AddField(
            model_name='sportevent',
            name='match_status',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='start_time_confirmed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='stats.Team'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
