# Generated by Django 3.0.dev20190304153508 on 2019-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20190324_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='api_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
