# Generated by Django 3.0.dev20190304153508 on 2019-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_sportevent_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='blocks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='field_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='goals_scored',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='red_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='saves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='seven_m_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='steals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='suspensions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='technical_fouls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='yellow_cards',
            field=models.IntegerField(null=True),
        ),
    ]
