# Generated by Django 3.0.dev20190304153508 on 2019-03-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_auto_20190326_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competition_ids',
        ),
        migrations.AddField(
            model_name='team',
            name='season_ids',
            field=models.ManyToManyField(to='stats.Season'),
        ),
    ]
