# Generated by Django 3.0.dev20190304153508 on 2019-08-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_team_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
