# Generated by Django 3.0.dev20190304153508 on 2019-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20190807_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
