# Generated by Django 3.0.dev20190304153508 on 2019-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyplayer',
            name='favorite_player',
            field=models.CharField(default='Siffert4ever', max_length=256),
        ),
    ]
