# Generated by Django 3.0.dev20190304153508 on 2019-08-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190812_2334'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyplayer',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='fantasyseason',
            name='season_ptr',
        ),
        migrations.RemoveField(
            model_name='fantasystatistic',
            name='statistic_ptr',
        ),
        migrations.RemoveField(
            model_name='fantasyteam',
            name='team_ptr',
        ),
        migrations.RemoveField(
            model_name='fantasyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fantasyvenue',
            name='venue_ptr',
        ),
        migrations.DeleteModel(
            name='FantasyCompetition',
        ),
        migrations.DeleteModel(
            name='FantasyPlayer',
        ),
        migrations.DeleteModel(
            name='FantasySeason',
        ),
        migrations.DeleteModel(
            name='FantasyStatistic',
        ),
        migrations.DeleteModel(
            name='FantasyTeam',
        ),
        migrations.DeleteModel(
            name='FantasyUser',
        ),
        migrations.DeleteModel(
            name='FantasyVenue',
        ),
    ]
