# Generated by Django 3.0.dev20190304153508 on 2019-08-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='team_ids',
            new_name='teams',
        ),
        migrations.RenameField(
            model_name='sportevent',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='sportevent',
            old_name='winner_id',
            new_name='winner',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='season_ids',
            new_name='seasons',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='base.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Venue'),
        ),
    ]
